### ISSUE TITLE
running from docker desktop Windows11 Mixbus (ardour)

### ISSUE THREAD

**Issue by stevespaw** [tv2/sisyfos-audio-controller#229]
I have run the command with PS:
docker run --volume /opt/sisyfos-audio-controller:/opt/sisyfos-audio-controller/storage -p 1176:1176 -p 5255:5255 -p 5255:5255/udp --network="host" --restart always olzzon/sisyfos-audio-controller:develop

With the network=host I cannot connect to webserver
When I remove that I can connect, but I cannot seem to connect to mixbus, everything is enabled - and on port 3819.

Here is with the above command:

PS C:\Users\steve> docker run --volume /opt/sisyfos-audio-controller:/opt/sisyfos-audio-controller/storage -p 1176:1176 -p 5255:5255 -p 5255:5255/udp -p 3819:3819/udp  --restart always olzzon/sisyfos-audio-controller:develop
yarn run v1.19.1
$ node dist/server/index.js
info: OSC listening on port 1234
info: OSC Automation listening on port 5255
info: Skaarhoj server listening at port 9923
info: Server started at http://localhost:1176
info: Setting up MainThreadHandlers
info: SETTINGS UP STATE
info: Initialising WebServer
info: Receiving state of desk
info: Listening for Automation via OSC over UDP.
info: Client connected :PVd70I8t52kwKQ4wAAAA
info: SETTING UP SOCKET IO MAIN HANDLERS
info: Client connected :7f9werBaw8ji2zoeAAAB
info: SETTING UP SOCKET IO MAIN HANDLERS
info: Client connected :eJEP4vDwJQ9YfUpuAAAC
info: SETTING UP SOCKET IO MAIN HANDLERS
socket subscribe vu
socket subscribe vu
socket subscribe vu
info: Client connected :VEIRuin3t6xJ-JCAAAAG
info: SETTING UP SOCKET IO MAIN HANDLERS
socket subscribe vu
info: Get snapshot list
info: Get CCG settings list
info: Get Preset list
info: Get custom pages list
{"level":"error","message":"Couldn´t read pages.json file"}
error: Couldn´t read pages.json file
info: Settings initial store on :VEIRuin3t6xJ-JCAAAAG
info: Settings initial store on :VEIRuin3t6xJ-JCAAAAG
info: Save settings :[object Object]
{"level":"error","message":"Error writing settings.json file: "}
error: Error writing settings.json file:
info: Client connected :ltONpQGTSN4BraiLAAAI
info: SETTING UP SOCKET IO MAIN HANDLERS
socket subscribe vu
info: Get snapshot list
info: Get CCG settings list
info: Get Preset list
info: Get custom pages list
{"level":"error","message":"Couldn´t read pages.json file"}
error: Couldn´t read pages.json file
info: Settings initial store on :ltONpQGTSN4BraiLAAAI
info: Settings initial store on :ltONpQGTSN4BraiLAAAI
/opt/sisyfos-audio-controller/dist/server/utils/mixerConnections/OscMixerConnection.js:390
            .AUX_LEVEL[0];
                      ^

TypeError: Cannot read property '0' of undefined
    at OscMixerConnection.updateAuxLevel (/opt/sisyfos-audio-controller/dist/server/utils/mixerConnections/OscMixerConnection.js:390:23)
    at OscMixerConnection.updateNextAux (/opt/sisyfos-audio-controller/dist/server/utils/mixerConnections/OscMixerConnection.js:372:14)
    at /opt/sisyfos-audio-controller/dist/server/utils/MixerConnection.js:149:59
    at Array.forEach (<anonymous>)
    at /opt/sisyfos-audio-controller/dist/server/utils/MixerConnection.js:147:43
    at Array.forEach (<anonymous>)
    at MixerGenericConnection.updateNextAux (/opt/sisyfos-audio-controller/dist/server/utils/MixerConnection.js:146:57)
    at Socket.<anonymous> (/opt/sisyfos-audio-controller/dist/server/MainThreadHandler.js:235:50)
    at Socket.emit (events.js:210:5)
    at Socket.emitUntyped (/opt/sisyfos-audio-controller/node_modules/socket.io/dist/typed-events.js:69:22)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
PS C:\Users\steve> docker run --volume /opt/sisyfos-audio-controller:/opt/sisyfos-audio-controller/storage -p 1176:1176 -p 5255:5255 -p 5255:5255/udp -p 3819:3819/udp  --restart always olzzon/sisyfos-audio-controller:develop
yarn run v1.19.1
$ node dist/server/index.js
info: OSC listening on port 3819
info: OSC Automation listening on port 5255
info: Skaarhoj server listening at port 9923
info: Server started at http://localhost:1176
info: Setting up MainThreadHandlers
info: SETTINGS UP STATE
info: Initialising WebServer
{"level":"error","message":"Error : Error: bind EADDRNOTAVAIL 192.168.2.104:3819"}
error: Error : Error: bind EADDRNOTAVAIL 192.168.2.104:3819
info: Listening for Automation via OSC over UDP.
info: Client connected :xjtloNfrOK6DMr8xAAAA
info: SETTING UP SOCKET IO MAIN HANDLERS
socket subscribe vu
info: Client connected :BiXOfL491BgclyJ6AAAC
info: SETTING UP SOCKET IO MAIN HANDLERS
socket subscribe vu
info: Client connected :YwcDN6ql956jk80HAAAE
info: SETTING UP SOCKET IO MAIN HANDLERS
socket subscribe vu
info: Receiving state of desk
/opt/sisyfos-audio-controller/dist/server/utils/mixerConnections/OscMixerConnection.js:390
            .AUX_LEVEL[0];
                      ^

TypeError: Cannot read property '0' of undefined
    at OscMixerConnection.updateAuxLevel (/opt/sisyfos-audio-controller/dist/server/utils/mixerConnections/OscMixerConnection.js:390:23)
    at OscMixerConnection.updateNextAux (/opt/sisyfos-audio-controller/dist/server/utils/mixerConnections/OscMixerConnection.js:372:14)
    at /opt/sisyfos-audio-controller/dist/server/utils/MixerConnection.js:149:59
    at Array.forEach (<anonymous>)
    at /opt/sisyfos-audio-controller/dist/server/utils/MixerConnection.js:147:43
    at Array.forEach (<anonymous>)
    at MixerGenericConnection.updateNextAux (/opt/sisyfos-audio-controller/dist/server/utils/MixerConnection.js:146:57)
    at Socket.<anonymous> (/opt/sisyfos-audio-controller/dist/server/MainThreadHandler.js:235:50)
    at Socket.emit (events.js:210:5)
    at Socket.emitUntyped (/opt/sisyfos-audio-controller/node_modules/socket.io/dist/typed-events.js:69:22)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
PS C:\Users\steve> docker run --volume /opt/sisyfos-audio-controller:/opt/sisyfos-audio-controller/storage -p 1176:1176 -p 5255:5255 -p 5255:5255/udp --network="host" --restart always olzzon/sisyfos-audio-controller:develop
WARNING: Published ports are discarded when using host network mode
yarn run v1.19.1
$ node dist/server/index.js
info: OSC listening on port 3819
info: OSC Automation listening on port 5255
info: Skaarhoj server listening at port 9923
info: Server started at http://localhost:1176
info: Setting up MainThreadHandlers
info: SETTINGS UP STATE
info: Initialising WebServer
{"level":"error","message":"Error : Error: bind EADDRNOTAVAIL 192.168.2.104:3819"}
error: Error : Error: bind EADDRNOTAVAIL 192.168.2.104:3819
info: Listening for Automation via OSC over UDP.
info: Receiving state of desk

**Comment by stevespaw** [comment]
I am new to Docker - Is it possible to build this for Win x64?

**Comment by olzzon** [comment]
Hi Steve,
Thanks a lot for the feedback. 
I think we need to check some stuff out for it to work on Ardour (it haven't been used for a long long time)

Btw it's possible to build Sisyfos as a windows app (use:  yarn electron-builder -w) hopefully a prebuild .exe file can be a part of the release later on.
